# a) Độ dài của vector

In [ ]:
import numpy as np

def compute_vector_length(vector):
    # cach 1
    len_of_vector1 = np.sqrt(np.dot(vector, vector))
    print("Cach 1:",len_of_vector1)
    # cach 2
    len_of_vector2 = np.linalg.norm(vector)
    print("Cach 2:",len_of_vector2)

    return len_of_vector1

# test
vector = np.array([1,2])
compute_vector_length(vector)

Cach 1: 2.23606797749979
Cach 2: 2.23606797749979


2.23606797749979

# b) Phép tích vô hướng

In [ ]:
import numpy as np

def compute_dot_product(vector1, vector2):
    # cach 1:
    result = np.dot(vector1,vector2)
    # cach 2:
    result = np.sum(vector1*vector2)
    return result

vector1 = np.array([1,2])
vector2 = np.array([3,4])
compute_dot_product(vector1, vector2)

11

# c) Nhân vector với ma trận

In [ ]:
import numpy as np

def nhanvectovoimatran(vector,matrix):
    result = np.dot(matrix,vector)
    return result

vector = np.array([1,2])
matrix = np.array([[1,2],[3,4]])
nhanvectovoimatran(vector,matrix)

array([ 5, 11])

# d) Nhân ma trận với ma trận

In [ ]:
import numpy as np

def nhan2matran(matrix1,matrix2):
    result = np.dot(matrix1,matrix2)
    return result

matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])
nhan2matran(matrix1,matrix2)

array([[19, 22],
       [43, 50]])

# e) Ma trận nghịch đảo

Matrix A:
$
A =
\begin{bmatrix}   
-2& 6\\
8 &-4\\
\end
{bmatrix}
, A ∈ R^{2*2}$

Determinant of A
$A ∈ R^{2*2}: det(A) = (-2 * -4) - (6 * 8) = -40 $

$det(A) = - 40 $

Inverse Matrix: $ A^{-1} = {1 \over det(A)}  
\begin{bmatrix}   
-4& -6\\
-8 &-2\\
\end{bmatrix}$


In [1]:
import numpy as np

def inverse_matrix(matrix):
    det = np.linalg.det(matrix)
    print(det)
    if det ==0:
        print("Matrix is not invertible")
        return None

    matrix2 = np.zeros((2,2))
    matrix2[0,0] = matrix[1,1]
    matrix2[0,1] = -matrix[0,1]
    matrix2[1,0] = -matrix[1,0]
    matrix2[1,1] = matrix[0,0]

    inverse_matrix = matrix2/det
    return inverse_matrix

matrix = np.array([[1,2],[3,4]])
inverse_matrix(matrix)

-2.0000000000000004


array([[-2. ,  1. ],
       [ 1.5, -0.5]])