In [5]:
import numpy as np

def compute_vector_length(vector):
    len_of_vector = np.linalg.norm(vector)
    return len_of_vector

vector = np.array([-2, 4, 9, 21])
result = compute_vector_length([vector])
print(round(result, 2))

23.28


In [8]:
import numpy as np

def compute_dot_product(vector1, vector2):
    result = np.dot(vector1,vector2)
    print(round(result,2))

vector1 = np.array([0, 1, -1, 2])
vector2 = np.array([2, 5, 1, 0])
compute_dot_product(vector1, vector2)

4


In [9]:
x = np.array([[1, 2],[3, 4]])
k = np.array([1, 2])
print('result \n', x.dot(k))

result 
 [ 5 11]


In [10]:
x = np.array([[-1, 2],[3, -4]])
k = np.array([1, 2])
print('result \n', x@k)

result 
 [ 3 -5]


In [11]:
def nhanvectovoimatran(vector,matrix):
    result = np.dot(matrix,vector)
    return result

vector = np.array([0,2,1])
matrix = np.array([[-1, 1, 1],[0, -4, 9]])
nhanvectovoimatran(vector,matrix)


array([3, 1])

In [12]:
def nhan2matran(matrix1,matrix2):
    result = np.dot(matrix1,matrix2)
    return result

matrix1 = np.array([[0,1,2],[2,-3,1]])
matrix2 = np.array([[1,-3],[6,1],[0,-1]])
nhan2matran(matrix1,matrix2)

array([[  6,  -1],
       [-16, -10]])

In [16]:
m1 = np.eye(3)
m2 = np.array([[1, 1, 1],[2, 2, 2],[3, 3, 3]])
result = m1@m2
print(result)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [23]:
m1 = np.eye(2)
m1 = np.reshape(m1,(-1,4))[0]
m2 = np.array([[1, 1, 1, 1],[2, 2, 2, 2],[3, 3, 3, 3],[4, 4, 4, 4]])
result = m1@m2
print(result)

[5. 5. 5. 5.]


In [27]:
m1 = np.array([[1, 2], [3, 4]])
m1 = np.reshape(m1, (-1,4),"F")[0]
print(m1)
m2 = np.array([[1, 1, 1, 1],[2, 2, 2, 2],[3, 3, 3, 3],[4, 4, 4, 4]])
result = m1@m2
print(result)

[1 3 2 4]
[29 29 29 29]


In [28]:
def inverse_matrix(matrix):
    det = np.linalg.det(matrix)
    print(det)
    if det ==0:
        print("Matrix is not invertible")
        return None

    matrix2 = np.zeros((2,2))
    matrix2[0,0] = matrix[1,1]
    matrix2[0,1] = -matrix[0,1]
    matrix2[1,0] = -matrix[1,0]
    matrix2[1,1] = matrix[0,0]

    inverse_matrix = matrix2/det
    return inverse_matrix

matrix = np.array([[-2,6],[8,-4]])
inverse_matrix(matrix)

-39.99999999999998


array([[0.1 , 0.15],
       [0.2 , 0.05]])

In [29]:
def compute_eigenvalues_eigenvectors(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    return eigenvalues, eigenvectors

matrix = np.array([[0.9, 0.2], [0.1, 0.8]])
eigenvalues, eigenvectors = compute_eigenvalues_eigenvectors(matrix)
print(eigenvectors)

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [34]:
def compute_cosine(v1, v2):
    if np.linalg.norm(v1) == 0 or np.linalg.norm(v2) == 0:
        result =  "None"
    else:
        result = round(np.dot(v1,v2) / (np.linalg.norm(v1) * np.linalg.norm(v2)),3)
    return result

vector1 = np.array([1, 2, 3, 4])
vector2 = np.array([1, 0, 3, 0])
print(compute_cosine(vector1, vector2))

0.577
